### ISSUE TITLE
Usage of this library in my own work

### ISSUE THREAD

**Issue by MetalTurtle18** [Scarsz/Configuralize#1]
This seems really useful for a project I am making. My only question is what I need to do to use this, license wise. Do I need to credit you in the code, include a copy of your license, do nothing, or can I not use this (I hope I can!).

Thank you

**Comment by Scarsz** [comment]
Went ahead and added a [`LICENSE`](https://github.com/Scarsz/Configuralize/blob/master/LICENSE) file, feel free to do whatever you'd like with the library

**Comment by MetalTurtle18** [comment]
Thanks!
